apiVersion: apps/v1
kind: Deployment
metadata:
  name: albion-rmt-backend
  namespace: albion-rmt-backend
  labels:
    app: albion-rmt-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: albion-rmt-backend
  template:
    metadata:
      name: albion-rmt-backend
      labels:
        app: albion-rmt-backend
    spec:
      containers:
        - name: albion-rmt-backend
          livenessProbe:
            httpGet:
              port: 8080
              path: /health
          image: ghcr.io/vaynerakawalo/albion-rmt-backend:latest
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: DB_URL
              value: "albion-db:5432/albion-db"
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: albion-db-config
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: albion-db-config
                  key: POSTGRES_PASSWORD

      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: albion-rmt-backend
  namespace: albion-rmt-backend
spec:
  selector:
    app: albion-rmt-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
