name: build-and-publish

run-name: Publishing docker image from branch '${{ github.head_ref || github.ref_name }}' by @${{ github.actor }}

on:
  push:
    branches:
      - main

env:
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish-image:
    name: publish-image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - run: echo "Publishing docker image from branch ${{ github.head_ref || github.ref_name }} triggered by @${{ github.actor }}"

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Get short SHA
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: graalvm
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Jar
        run: ./gradlew bootJar

      - name: Extract jar layers
        run: |
          mv build/libs/*.jar application.jar
          java -Djarmode=tools -jar application.jar extract --layers --destination extracted

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ env.SHORT_SHA }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Finally
        run: echo "Successfully created docker image with tag ${{ env.SHORT_SHA }}"
