name: Build and Publish

run-name: Publishing docker image from branch '${{ github.head_ref || github.ref_name }}' by @${{ github.actor }}

on:
  push:
    branches:
      - main

jobs:
  publish-image:
    name: publish-image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - run: echo "Publishing docker image from branch ${{ github.head_ref || github.ref_name }} triggered by @${{ github.actor }}"

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Get short SHA
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ env.SHORT_SHA }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Finally
        run: echo "Successfully created docker image with tag ${{ env.SHORT_SHA }}"
